//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NDDDSample.RegisterApp.HandlingReportService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HandlingReport", Namespace="http://schemas.datacontract.org/2004/07/NDDDSample.Interfaces.HandlingService.Web" +
        "Service")]
    [System.SerializableAttribute()]
    public partial class HandlingReport : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Nullable<System.DateTime> CompletionTimeField;
        
        private string[] TrackingIdsField;
        
        private string TypeField;
        
        private string UnLocodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VoyageNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<System.DateTime> CompletionTime {
            get {
                return this.CompletionTimeField;
            }
            set {
                if ((this.CompletionTimeField.Equals(value) != true)) {
                    this.CompletionTimeField = value;
                    this.RaisePropertyChanged("CompletionTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string[] TrackingIds {
            get {
                return this.TrackingIdsField;
            }
            set {
                if ((object.ReferenceEquals(this.TrackingIdsField, value) != true)) {
                    this.TrackingIdsField = value;
                    this.RaisePropertyChanged("TrackingIds");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string UnLocode {
            get {
                return this.UnLocodeField;
            }
            set {
                if ((object.ReferenceEquals(this.UnLocodeField, value) != true)) {
                    this.UnLocodeField = value;
                    this.RaisePropertyChanged("UnLocode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VoyageNumber {
            get {
                return this.VoyageNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.VoyageNumberField, value) != true)) {
                    this.VoyageNumberField = value;
                    this.RaisePropertyChanged("VoyageNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HandlingReportException", Namespace="http://schemas.datacontract.org/2004/07/NDDDSample.Interfaces.HandlingService.Web" +
        "Service")]
    [System.SerializableAttribute()]
    public partial class HandlingReportException : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HandlingReportService.IHandlingReportService")]
    public interface IHandlingReportService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHandlingReportService/SubmitReport", ReplyAction="http://tempuri.org/IHandlingReportService/SubmitReportResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(NDDDSample.RegisterApp.HandlingReportService.HandlingReportException), Action="http://tempuri.org/IHandlingReportService/SubmitReportHandlingReportExceptionFaul" +
            "t", Name="HandlingReportException", Namespace="http://schemas.datacontract.org/2004/07/NDDDSample.Interfaces.HandlingService.Web" +
            "Service")]
        void SubmitReport(NDDDSample.RegisterApp.HandlingReportService.HandlingReport handlingReport);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IHandlingReportServiceChannel : NDDDSample.RegisterApp.HandlingReportService.IHandlingReportService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HandlingReportServiceClient : System.ServiceModel.ClientBase<NDDDSample.RegisterApp.HandlingReportService.IHandlingReportService>, NDDDSample.RegisterApp.HandlingReportService.IHandlingReportService {
        
        public HandlingReportServiceClient() {
        }
        
        public HandlingReportServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HandlingReportServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HandlingReportServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HandlingReportServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void SubmitReport(NDDDSample.RegisterApp.HandlingReportService.HandlingReport handlingReport) {
            base.Channel.SubmitReport(handlingReport);
        }
    }
}
